// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiMasterTemplate.Domain.DbContexts;

#nullable disable

namespace WebApiMasterTemplate.Domain.Migrations
{
    [DbContext(typeof(TaskPlannerDbContext))]
    [Migration("20220530031751_Added task tracker seed 2")]
    partial class Addedtasktrackerseed2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.TaskKeeper", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<long>("TaskTrackerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TaskTrackerId");

                    b.ToTable("Task", (string)null);
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.TaskTracker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("TaskTracker", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = 1L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(258),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(308),
                            Description = "Iusto qui velit ut quaerat vitae sint reiciendis ut neque.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(345),
                            Title = "Explicabo aut."
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = 1L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(428),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(430),
                            Description = "Animi molestias magni quia maxime.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(432),
                            Title = "Odio."
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = 1L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(478),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(479),
                            Description = "Modi culpa et qui consequatur incidunt.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(480),
                            Title = "Nam eligendi."
                        },
                        new
                        {
                            Id = 4L,
                            CreatedBy = 2L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(558),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(560),
                            Description = "Ullam et labore ut voluptates reiciendis.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(561),
                            Title = "Culpa."
                        },
                        new
                        {
                            Id = 5L,
                            CreatedBy = 2L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(617),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(618),
                            Description = "Enim sed magni magnam cumque cupiditate omnis dolores blanditiis ut.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(620),
                            Title = "Libero ipsum."
                        },
                        new
                        {
                            Id = 6L,
                            CreatedBy = 2L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(659),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(660),
                            Description = "Et atque dolorem eligendi veritatis.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(661),
                            Title = "Sit repudiandae."
                        },
                        new
                        {
                            Id = 7L,
                            CreatedBy = 3L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(705),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(706),
                            Description = "Aut ut consequatur ab sed consectetur nihil et.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(707),
                            Title = "Omnis."
                        },
                        new
                        {
                            Id = 8L,
                            CreatedBy = 3L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(760),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(761),
                            Description = "Ipsa fugiat consequatur atque et saepe qui quia accusamus.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(762),
                            Title = "Qui alias."
                        },
                        new
                        {
                            Id = 9L,
                            CreatedBy = 3L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(848),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(849),
                            Description = "Incidunt dolorem quae ex fugiat est ducimus saepe quas nisi.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(851),
                            Title = "Temporibus soluta."
                        },
                        new
                        {
                            Id = 10L,
                            CreatedBy = 4L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(896),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(897),
                            Description = "Voluptatem totam numquam repudiandae rerum ut consectetur.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(898),
                            Title = "Delectus eveniet."
                        },
                        new
                        {
                            Id = 11L,
                            CreatedBy = 4L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(942),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(943),
                            Description = "Error velit amet et dolor non earum doloribus.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(945),
                            Title = "Voluptatem."
                        },
                        new
                        {
                            Id = 12L,
                            CreatedBy = 4L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(986),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(987),
                            Description = "Maiores vero repellendus iste et praesentium sed.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(988),
                            Title = "Iure."
                        },
                        new
                        {
                            Id = 13L,
                            CreatedBy = 5L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1129),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1130),
                            Description = "Quibusdam dolore eveniet sint iste laudantium.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1131),
                            Title = "Consequuntur."
                        },
                        new
                        {
                            Id = 14L,
                            CreatedBy = 5L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1166),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1167),
                            Description = "Quis architecto aut repudiandae sit.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1201),
                            Title = "Alias."
                        },
                        new
                        {
                            Id = 15L,
                            CreatedBy = 5L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1240),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1241),
                            Description = "Suscipit minima odio facere expedita nisi.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1243),
                            Title = "Nemo."
                        },
                        new
                        {
                            Id = 16L,
                            CreatedBy = 6L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1276),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1277),
                            Description = "Consequatur neque ex eveniet qui.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1278),
                            Title = "Ut et."
                        },
                        new
                        {
                            Id = 17L,
                            CreatedBy = 6L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1325),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1326),
                            Description = "Et et quis sit quaerat at voluptatem qui qui.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1328),
                            Title = "Molestias possimus."
                        },
                        new
                        {
                            Id = 18L,
                            CreatedBy = 6L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1377),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1378),
                            Description = "Omnis fuga aut unde sunt fugit reiciendis molestias similique est.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1379),
                            Title = "Aut."
                        },
                        new
                        {
                            Id = 19L,
                            CreatedBy = 7L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1411),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1412),
                            Description = "Alias praesentium quae perspiciatis quia.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1413),
                            Title = "Facilis."
                        },
                        new
                        {
                            Id = 20L,
                            CreatedBy = 7L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1516),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1517),
                            Description = "Sequi dolor omnis qui pariatur tempora perspiciatis sunt.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1518),
                            Title = "Eum deserunt."
                        },
                        new
                        {
                            Id = 21L,
                            CreatedBy = 7L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1561),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1562),
                            Description = "Illum dolorum est consequatur possimus et sit.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1563),
                            Title = "Non."
                        },
                        new
                        {
                            Id = 22L,
                            CreatedBy = 8L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1602),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1603),
                            Description = "Amet maiores dignissimos nesciunt veniam.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1604),
                            Title = "Veritatis."
                        },
                        new
                        {
                            Id = 23L,
                            CreatedBy = 8L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1688),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1689),
                            Description = "Consequuntur illo est veritatis voluptatibus molestias quibusdam eius debitis maxime.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1690),
                            Title = "Est."
                        },
                        new
                        {
                            Id = 24L,
                            CreatedBy = 8L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1730),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1731),
                            Description = "Et porro alias rerum natus quisquam et.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1732),
                            Title = "Aspernatur."
                        },
                        new
                        {
                            Id = 25L,
                            CreatedBy = 9L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1780),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1838),
                            Description = "Et earum id quia quis fugit id non cupiditate sit.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1840),
                            Title = "Voluptates sed."
                        },
                        new
                        {
                            Id = 26L,
                            CreatedBy = 9L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1880),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1881),
                            Description = "Quaerat enim rem possimus totam.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1882),
                            Title = "Laborum enim."
                        },
                        new
                        {
                            Id = 27L,
                            CreatedBy = 9L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1916),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1917),
                            Description = "Illum aut aspernatur distinctio deleniti.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1918),
                            Title = "Ut error."
                        },
                        new
                        {
                            Id = 28L,
                            CreatedBy = 10L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1948),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1949),
                            Description = "Tenetur sapiente animi libero alias.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1950),
                            Title = "Velit."
                        },
                        new
                        {
                            Id = 29L,
                            CreatedBy = 10L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1995),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1996),
                            Description = "Voluptatem aut quo quia dolorem a natus magnam itaque tenetur.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(1997),
                            Title = "In."
                        },
                        new
                        {
                            Id = 30L,
                            CreatedBy = 10L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(2032),
                            Deadline = new DateTime(2022, 6, 6, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(2033),
                            Description = "Delectus ab ut maiores officia.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 424, DateTimeKind.Utc).AddTicks(2034),
                            Title = "Quis aperiam."
                        });
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 418, DateTimeKind.Utc).AddTicks(4748),
                            Email = "JermaineJacobson_Mraz@yahoo.com",
                            Name = "Jermaine Jacobson",
                            Password = "MfffsByeh1b83jcv7ZmvEOq3zR0A2c5vFRsFR_yH305_uvofiacdaX8qKBESVFfa5US6Zz_uAoHfxLUo56zU_WgpIp4FSaCpR2Xveg4j02J6C1xFB0pNL9unskBV8ZjS"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 418, DateTimeKind.Utc).AddTicks(5510),
                            Email = "JusticeBrekke14@yahoo.com",
                            Name = "Justice Brekke",
                            Password = "Laskl6xl8lygdj2BhZfBUeg1TOUIWfZsDRSYpiJJ7qBzn7gHVPfvFPThjnXC_MMvTpgT0hIq4vK0N3YxmUg_pFdsnb3TWAan44mDGtBeozeeQeYVSx_WeQc6FbH_Pz2G"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 418, DateTimeKind.Utc).AddTicks(6102),
                            Email = "SallyLesch_Witting87@hotmail.com",
                            Name = "Sally Lesch",
                            Password = "E55ttcQqS63rygYOowXuPAfiUALHY9UO2Pj8oTvy97wQxoQS3DavJKaL_18ez1Ix72O7NaOCsb1YAGcsDnYaI4r23lJjMN4jYTuT0T62DK_ScEQQhxHwOCrD99ORF1r9"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 418, DateTimeKind.Utc).AddTicks(6658),
                            Email = "JacyntheStracke_Runte58@yahoo.com",
                            Name = "Jacynthe Stracke",
                            Password = "6KksoYzaark5zkS7zRtILm2jFB3r9b5k27n5vrhvlibawfQNTpKcny98bK4Kgf4a3Hsku3QL7yVwESehiuyAB6tlKkmxX5xf5WGymx4yXVx2ZfxkyOyW8o8wb_sUAa5S"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 418, DateTimeKind.Utc).AddTicks(7174),
                            Email = "VallieKovacek.Friesen@yahoo.com",
                            Name = "Vallie Kovacek",
                            Password = "tHw3kGj4U9iHedfEyJQjCP25elsiUhWIzSpFTEVyKkpXt5Z2ryuXHW1Voc6NjhzVccrA66nn_bep3ZrWGoXNOib2zwDapxRUimj2Ff8rdGFDutZ0Rr30t0LZcQiIvWen"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 418, DateTimeKind.Utc).AddTicks(7696),
                            Email = "ChristTurner_Yundt68@gmail.com",
                            Name = "Christ Turner",
                            Password = "hipr8SU0NHvHk5n98jE6_efJ4DENw5va3ovVrPTScc0u90LBPkVEqsSLHmk5ddIck1XjvIEMlrSSZC_E2uIK3cJL7T5H4LyZlabbYSndzGEbw8MbPItxO82N8GijAo_i"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 418, DateTimeKind.Utc).AddTicks(8278),
                            Email = "EstrellaHermann_Gerlach@hotmail.com",
                            Name = "Estrella Hermann",
                            Password = "NgvWuKBUmkc99dIVUPOKBuyMzrMilm5YoBkaLTDxOUkY5ItcfeWwSMPFbmkrzkhPdEEQuQfTSjQ_fKy2vqIX60MGEJ2IV87IGKMkRoYmOwl_hDNjan_WP9uHx3Mb52HX"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 418, DateTimeKind.Utc).AddTicks(8810),
                            Email = "KaraHegmann.Macejkovic10@gmail.com",
                            Name = "Kara Hegmann",
                            Password = "Q15koOiLB75gefbpvizARwL9KcaIK8apxYF5zUOMll9xyi6JqTJuFx_jo5VhdNSocpjcBcuDIAPGlMFltK2x1Ui7Ta_fbI9fusxHFiawnOpnf88gLfG2PH8An3whyDV0"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 418, DateTimeKind.Utc).AddTicks(9359),
                            Email = "LeonelHand.Littel4@yahoo.com",
                            Name = "Leonel Hand",
                            Password = "BqYOX75FSQgXcWknxcvVRowDsVjsPD6WRxMJNfwD4tmNMmmcYD4b2Lfk3nD4uAeOlba_va4p5sUf4DL_Suv5tA0_bRFX6V3CYD9vJhHjFlBWaSIlPyJF5HBshm8yZ160"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 17, 51, 418, DateTimeKind.Utc).AddTicks(9985),
                            Email = "EttieSchmidt.Kshlerin@yahoo.com",
                            Name = "Ettie Schmidt",
                            Password = "sA9Zfka0edqavutySCUrltT0c1b6Niu2gNppzJnpKQwbZGxILNTW_ZJaFM1xcdF5V79FvKSTd_aH9yIw_GQYx0HmvAN9l82yGRfXf5piUCJIWYRjEDrjDXe0bZK9NY9r"
                        });
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.TaskKeeper", b =>
                {
                    b.HasOne("WebApiMasterTemplate.Domain.DbModels.TaskTracker", "TaskTracker")
                        .WithMany("TaskKeepers")
                        .HasForeignKey("TaskTrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskTracker");
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.TaskTracker", b =>
                {
                    b.HasOne("WebApiMasterTemplate.Domain.DbModels.User", "User")
                        .WithMany("TaskTrackers")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.TaskTracker", b =>
                {
                    b.Navigation("TaskKeepers");
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.User", b =>
                {
                    b.Navigation("TaskTrackers");
                });
#pragma warning restore 612, 618
        }
    }
}
