// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiMasterTemplate.Domain.DbContexts;

#nullable disable

namespace WebApiMasterTemplate.Domain.Migrations
{
    [DbContext(typeof(TaskPlannerDbContext))]
    [Migration("20220530033105_Added task keeper seed")]
    partial class Addedtaskkeeperseed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.TaskKeeper", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<long>("TaskTrackerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TaskTrackerId");

                    b.ToTable("Task", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 1L,
                            Title = "Exercitationem."
                        },
                        new
                        {
                            Id = 2L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 1L,
                            Title = "Omnis inventore."
                        },
                        new
                        {
                            Id = 3L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 1L,
                            Title = "Illum."
                        },
                        new
                        {
                            Id = 4L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 1L,
                            Title = "Voluptate quos."
                        },
                        new
                        {
                            Id = 5L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 1L,
                            Title = "Blanditiis id."
                        },
                        new
                        {
                            Id = 6L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 2L,
                            Title = "Beatae ea."
                        },
                        new
                        {
                            Id = 7L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 2L,
                            Title = "Assumenda voluptatum."
                        },
                        new
                        {
                            Id = 8L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 2L,
                            Title = "Saepe."
                        },
                        new
                        {
                            Id = 9L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 2L,
                            Title = "Libero facere."
                        },
                        new
                        {
                            Id = 10L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 2L,
                            Title = "Doloremque odio."
                        },
                        new
                        {
                            Id = 11L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 3L,
                            Title = "Asperiores."
                        },
                        new
                        {
                            Id = 12L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 3L,
                            Title = "Et quo."
                        },
                        new
                        {
                            Id = 13L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 3L,
                            Title = "Consequatur facilis."
                        },
                        new
                        {
                            Id = 14L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 3L,
                            Title = "Sed."
                        },
                        new
                        {
                            Id = 15L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 3L,
                            Title = "Aut."
                        },
                        new
                        {
                            Id = 16L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 4L,
                            Title = "Natus."
                        },
                        new
                        {
                            Id = 17L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 4L,
                            Title = "Dolor."
                        },
                        new
                        {
                            Id = 18L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 4L,
                            Title = "Cumque."
                        },
                        new
                        {
                            Id = 19L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 4L,
                            Title = "Harum ducimus."
                        },
                        new
                        {
                            Id = 20L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 4L,
                            Title = "Placeat sunt."
                        },
                        new
                        {
                            Id = 21L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 5L,
                            Title = "Sapiente."
                        },
                        new
                        {
                            Id = 22L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 5L,
                            Title = "Aut dolor."
                        },
                        new
                        {
                            Id = 23L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 5L,
                            Title = "Voluptatem."
                        },
                        new
                        {
                            Id = 24L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 5L,
                            Title = "Debitis."
                        },
                        new
                        {
                            Id = 25L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 5L,
                            Title = "Voluptas."
                        },
                        new
                        {
                            Id = 26L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 6L,
                            Title = "Voluptatem."
                        },
                        new
                        {
                            Id = 27L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 6L,
                            Title = "Nulla."
                        },
                        new
                        {
                            Id = 28L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 6L,
                            Title = "Rem quo."
                        },
                        new
                        {
                            Id = 29L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 6L,
                            Title = "Ut."
                        },
                        new
                        {
                            Id = 30L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 6L,
                            Title = "Illum eius."
                        },
                        new
                        {
                            Id = 31L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 7L,
                            Title = "Distinctio voluptatum."
                        },
                        new
                        {
                            Id = 32L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 7L,
                            Title = "Nisi."
                        },
                        new
                        {
                            Id = 33L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 7L,
                            Title = "Culpa iste."
                        },
                        new
                        {
                            Id = 34L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 7L,
                            Title = "Saepe."
                        },
                        new
                        {
                            Id = 35L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 7L,
                            Title = "Qui."
                        },
                        new
                        {
                            Id = 36L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 8L,
                            Title = "Odit."
                        },
                        new
                        {
                            Id = 37L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 8L,
                            Title = "Nesciunt in."
                        },
                        new
                        {
                            Id = 38L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 8L,
                            Title = "Quo."
                        },
                        new
                        {
                            Id = 39L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 8L,
                            Title = "Eius a."
                        },
                        new
                        {
                            Id = 40L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 8L,
                            Title = "Quia quam."
                        },
                        new
                        {
                            Id = 41L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 9L,
                            Title = "Aut."
                        },
                        new
                        {
                            Id = 42L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 9L,
                            Title = "Quae."
                        },
                        new
                        {
                            Id = 43L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 9L,
                            Title = "Odio."
                        },
                        new
                        {
                            Id = 44L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 9L,
                            Title = "Sed."
                        },
                        new
                        {
                            Id = 45L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 9L,
                            Title = "Quis."
                        },
                        new
                        {
                            Id = 46L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 10L,
                            Title = "Quisquam ratione."
                        },
                        new
                        {
                            Id = 47L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 10L,
                            Title = "Aut."
                        },
                        new
                        {
                            Id = 48L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 10L,
                            Title = "Modi."
                        },
                        new
                        {
                            Id = 49L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 10L,
                            Title = "Cupiditate."
                        },
                        new
                        {
                            Id = 50L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 10L,
                            Title = "Ut quod."
                        },
                        new
                        {
                            Id = 51L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 11L,
                            Title = "Iure rerum."
                        },
                        new
                        {
                            Id = 52L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 11L,
                            Title = "Rerum est."
                        },
                        new
                        {
                            Id = 53L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 11L,
                            Title = "Aspernatur."
                        },
                        new
                        {
                            Id = 54L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 11L,
                            Title = "Explicabo."
                        },
                        new
                        {
                            Id = 55L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 11L,
                            Title = "Facere."
                        },
                        new
                        {
                            Id = 56L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 12L,
                            Title = "Nostrum."
                        },
                        new
                        {
                            Id = 57L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 12L,
                            Title = "Facere."
                        },
                        new
                        {
                            Id = 58L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 12L,
                            Title = "Debitis."
                        },
                        new
                        {
                            Id = 59L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 12L,
                            Title = "Dolores."
                        },
                        new
                        {
                            Id = 60L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 12L,
                            Title = "Est laboriosam."
                        },
                        new
                        {
                            Id = 61L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 13L,
                            Title = "Aperiam."
                        },
                        new
                        {
                            Id = 62L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 13L,
                            Title = "Quia odio."
                        },
                        new
                        {
                            Id = 63L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 13L,
                            Title = "Repellendus quaerat."
                        },
                        new
                        {
                            Id = 64L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 13L,
                            Title = "Perspiciatis."
                        },
                        new
                        {
                            Id = 65L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 13L,
                            Title = "Voluptatum incidunt."
                        },
                        new
                        {
                            Id = 66L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 14L,
                            Title = "Et."
                        },
                        new
                        {
                            Id = 67L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 14L,
                            Title = "Et doloremque."
                        },
                        new
                        {
                            Id = 68L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 14L,
                            Title = "Sed."
                        },
                        new
                        {
                            Id = 69L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 14L,
                            Title = "Quisquam."
                        },
                        new
                        {
                            Id = 70L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 14L,
                            Title = "Ratione."
                        },
                        new
                        {
                            Id = 71L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 15L,
                            Title = "Ut qui."
                        },
                        new
                        {
                            Id = 72L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 15L,
                            Title = "Ea quisquam."
                        },
                        new
                        {
                            Id = 73L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 15L,
                            Title = "Laudantium est."
                        },
                        new
                        {
                            Id = 74L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 15L,
                            Title = "Unde."
                        },
                        new
                        {
                            Id = 75L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 15L,
                            Title = "Occaecati."
                        },
                        new
                        {
                            Id = 76L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 16L,
                            Title = "Provident quis."
                        },
                        new
                        {
                            Id = 77L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 16L,
                            Title = "Voluptatum voluptatem."
                        },
                        new
                        {
                            Id = 78L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 16L,
                            Title = "Nobis."
                        },
                        new
                        {
                            Id = 79L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 16L,
                            Title = "Pariatur."
                        },
                        new
                        {
                            Id = 80L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 16L,
                            Title = "Aliquam."
                        },
                        new
                        {
                            Id = 81L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 17L,
                            Title = "Reiciendis quis."
                        },
                        new
                        {
                            Id = 82L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 17L,
                            Title = "Sed."
                        },
                        new
                        {
                            Id = 83L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 17L,
                            Title = "Quia."
                        },
                        new
                        {
                            Id = 84L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 17L,
                            Title = "Rerum perspiciatis."
                        },
                        new
                        {
                            Id = 85L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 17L,
                            Title = "Saepe."
                        },
                        new
                        {
                            Id = 86L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 18L,
                            Title = "Sapiente."
                        },
                        new
                        {
                            Id = 87L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 18L,
                            Title = "Aut."
                        },
                        new
                        {
                            Id = 88L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 18L,
                            Title = "Nemo."
                        },
                        new
                        {
                            Id = 89L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 18L,
                            Title = "Quis tenetur."
                        },
                        new
                        {
                            Id = 90L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 18L,
                            Title = "Ex."
                        },
                        new
                        {
                            Id = 91L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 19L,
                            Title = "Et optio."
                        },
                        new
                        {
                            Id = 92L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 19L,
                            Title = "Aut ipsa."
                        },
                        new
                        {
                            Id = 93L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 19L,
                            Title = "Est voluptatum."
                        },
                        new
                        {
                            Id = 94L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 19L,
                            Title = "Dolorum."
                        },
                        new
                        {
                            Id = 95L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 19L,
                            Title = "Cupiditate."
                        },
                        new
                        {
                            Id = 96L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 20L,
                            Title = "Fugiat id."
                        },
                        new
                        {
                            Id = 97L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 20L,
                            Title = "Blanditiis ut."
                        },
                        new
                        {
                            Id = 98L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 20L,
                            Title = "Minima."
                        },
                        new
                        {
                            Id = 99L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 20L,
                            Title = "Veritatis eius."
                        },
                        new
                        {
                            Id = 100L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 20L,
                            Title = "Eos impedit."
                        },
                        new
                        {
                            Id = 101L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 21L,
                            Title = "Voluptas dolorem."
                        },
                        new
                        {
                            Id = 102L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 21L,
                            Title = "Ipsam."
                        },
                        new
                        {
                            Id = 103L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 21L,
                            Title = "Sint."
                        },
                        new
                        {
                            Id = 104L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 21L,
                            Title = "Facere."
                        },
                        new
                        {
                            Id = 105L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 21L,
                            Title = "Blanditiis perspiciatis."
                        },
                        new
                        {
                            Id = 106L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 22L,
                            Title = "Reprehenderit dolorum."
                        },
                        new
                        {
                            Id = 107L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 22L,
                            Title = "Ducimus."
                        },
                        new
                        {
                            Id = 108L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 22L,
                            Title = "Ut."
                        },
                        new
                        {
                            Id = 109L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 22L,
                            Title = "Sint id."
                        },
                        new
                        {
                            Id = 110L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 22L,
                            Title = "Commodi."
                        },
                        new
                        {
                            Id = 111L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 23L,
                            Title = "Perferendis ut."
                        },
                        new
                        {
                            Id = 112L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 23L,
                            Title = "Non."
                        },
                        new
                        {
                            Id = 113L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 23L,
                            Title = "Qui."
                        },
                        new
                        {
                            Id = 114L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 23L,
                            Title = "Est tempore."
                        },
                        new
                        {
                            Id = 115L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 23L,
                            Title = "Quam."
                        },
                        new
                        {
                            Id = 116L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 24L,
                            Title = "Est deleniti."
                        },
                        new
                        {
                            Id = 117L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 24L,
                            Title = "Voluptas."
                        },
                        new
                        {
                            Id = 118L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 24L,
                            Title = "Inventore et."
                        },
                        new
                        {
                            Id = 119L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 24L,
                            Title = "Tempora."
                        },
                        new
                        {
                            Id = 120L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 24L,
                            Title = "Qui."
                        },
                        new
                        {
                            Id = 121L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 25L,
                            Title = "Aliquid."
                        },
                        new
                        {
                            Id = 122L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 25L,
                            Title = "Molestiae."
                        },
                        new
                        {
                            Id = 123L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 25L,
                            Title = "Ea."
                        },
                        new
                        {
                            Id = 124L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 25L,
                            Title = "Doloribus."
                        },
                        new
                        {
                            Id = 125L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 25L,
                            Title = "Reiciendis."
                        },
                        new
                        {
                            Id = 126L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 26L,
                            Title = "Eum nemo."
                        },
                        new
                        {
                            Id = 127L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 26L,
                            Title = "Ut sint."
                        },
                        new
                        {
                            Id = 128L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 26L,
                            Title = "Aut."
                        },
                        new
                        {
                            Id = 129L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 26L,
                            Title = "Pariatur."
                        },
                        new
                        {
                            Id = 130L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 26L,
                            Title = "Id."
                        },
                        new
                        {
                            Id = 131L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 27L,
                            Title = "Provident."
                        },
                        new
                        {
                            Id = 132L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 27L,
                            Title = "Aut ut."
                        },
                        new
                        {
                            Id = 133L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 27L,
                            Title = "Ut."
                        },
                        new
                        {
                            Id = 134L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 27L,
                            Title = "Aut sed."
                        },
                        new
                        {
                            Id = 135L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 27L,
                            Title = "Molestias."
                        },
                        new
                        {
                            Id = 136L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 28L,
                            Title = "Et."
                        },
                        new
                        {
                            Id = 137L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 28L,
                            Title = "Omnis dolorem."
                        },
                        new
                        {
                            Id = 138L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 28L,
                            Title = "Magnam illo."
                        },
                        new
                        {
                            Id = 139L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 28L,
                            Title = "Optio dignissimos."
                        },
                        new
                        {
                            Id = 140L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 28L,
                            Title = "Eum."
                        },
                        new
                        {
                            Id = 141L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 3,
                            TaskTrackerId = 29L,
                            Title = "Iure repellat."
                        },
                        new
                        {
                            Id = 142L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 29L,
                            Title = "Numquam."
                        },
                        new
                        {
                            Id = 143L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 29L,
                            Title = "Velit voluptatem."
                        },
                        new
                        {
                            Id = 144L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 29L,
                            Title = "Veniam voluptas."
                        },
                        new
                        {
                            Id = 145L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 2,
                            TaskTrackerId = 29L,
                            Title = "Odit."
                        },
                        new
                        {
                            Id = 146L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 30L,
                            Title = "Ullam omnis."
                        },
                        new
                        {
                            Id = 147L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 30L,
                            Title = "Et dolor."
                        },
                        new
                        {
                            Id = 148L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 4,
                            TaskTrackerId = 30L,
                            Title = "Perferendis aut."
                        },
                        new
                        {
                            Id = 149L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 30L,
                            Title = "Quas."
                        },
                        new
                        {
                            Id = 150L,
                            Deadline = new DateTime(2022, 6, 3, 3, 31, 4, 866, DateTimeKind.Utc).AddTicks(1445),
                            State = 1,
                            TaskTrackerId = 30L,
                            Title = "Officia."
                        });
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.TaskTracker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("TaskTracker", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = 1L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(397),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(445),
                            Description = "Rerum et qui minus aspernatur minima sit nihil.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(488),
                            Title = "Rerum eos."
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = 1L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(593),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(596),
                            Description = "Fugit possimus voluptas inventore laudantium quo repellendus optio.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(598),
                            Title = "Et."
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = 1L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(648),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(650),
                            Description = "Et necessitatibus et aut voluptatum et consequatur aliquam.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(651),
                            Title = "Aliquid."
                        },
                        new
                        {
                            Id = 4L,
                            CreatedBy = 2L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(780),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(782),
                            Description = "Tenetur facilis repudiandae odit tenetur quod vel.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(783),
                            Title = "Dolorum quia."
                        },
                        new
                        {
                            Id = 5L,
                            CreatedBy = 2L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(827),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(828),
                            Description = "Culpa qui corrupti voluptatem ad et.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(829),
                            Title = "Asperiores ex."
                        },
                        new
                        {
                            Id = 6L,
                            CreatedBy = 2L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(872),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(873),
                            Description = "Exercitationem suscipit labore sed veniam facere saepe aut.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(874),
                            Title = "Eum."
                        },
                        new
                        {
                            Id = 7L,
                            CreatedBy = 3L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(918),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(920),
                            Description = "Tenetur qui inventore minus enim deserunt nostrum itaque provident dolor.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(921),
                            Title = "Doloribus."
                        },
                        new
                        {
                            Id = 8L,
                            CreatedBy = 3L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(971),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(972),
                            Description = "Dolore sunt dicta nemo non inventore quam beatae rerum.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(973),
                            Title = "Est."
                        },
                        new
                        {
                            Id = 9L,
                            CreatedBy = 3L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1067),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1068),
                            Description = "Ipsum ut consectetur occaecati dolor omnis commodi officiis cupiditate quidem.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1069),
                            Title = "Voluptas repellat."
                        },
                        new
                        {
                            Id = 10L,
                            CreatedBy = 4L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1112),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1113),
                            Description = "Consequatur asperiores qui est vel deleniti minus fugit.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1114),
                            Title = "Qui."
                        },
                        new
                        {
                            Id = 11L,
                            CreatedBy = 4L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1159),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1160),
                            Description = "Distinctio voluptatibus adipisci recusandae accusamus ut eligendi voluptatem voluptas.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1161),
                            Title = "Qui."
                        },
                        new
                        {
                            Id = 12L,
                            CreatedBy = 4L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1200),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1201),
                            Description = "Et molestias quis doloremque est aliquid.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1202),
                            Title = "Ea tempore."
                        },
                        new
                        {
                            Id = 13L,
                            CreatedBy = 5L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1241),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1242),
                            Description = "Sit qui quia rerum a molestias laborum.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1243),
                            Title = "Voluptatem et."
                        },
                        new
                        {
                            Id = 14L,
                            CreatedBy = 5L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1327),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1328),
                            Description = "Repellendus est expedita non maiores sint maiores provident beatae.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1330),
                            Title = "Illo fugit."
                        },
                        new
                        {
                            Id = 15L,
                            CreatedBy = 5L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1365),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1366),
                            Description = "Magni sunt itaque ut hic.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1367),
                            Title = "Esse voluptatibus."
                        },
                        new
                        {
                            Id = 16L,
                            CreatedBy = 6L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1401),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1402),
                            Description = "Assumenda occaecati enim repellendus et.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1403),
                            Title = "Tempora error."
                        },
                        new
                        {
                            Id = 17L,
                            CreatedBy = 6L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1440),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1442),
                            Description = "Aperiam doloremque laboriosam pariatur et nam reprehenderit.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1443),
                            Title = "Corrupti."
                        },
                        new
                        {
                            Id = 18L,
                            CreatedBy = 6L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1480),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1481),
                            Description = "Excepturi quia facere rerum vitae ipsam consequatur vero.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1482),
                            Title = "Harum."
                        },
                        new
                        {
                            Id = 19L,
                            CreatedBy = 7L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1518),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1519),
                            Description = "Nam earum recusandae nihil quis aperiam.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1520),
                            Title = "Sed nisi."
                        },
                        new
                        {
                            Id = 20L,
                            CreatedBy = 7L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1560),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1561),
                            Description = "Est fuga quia voluptatem voluptas possimus nihil.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1562),
                            Title = "Quis unde."
                        },
                        new
                        {
                            Id = 21L,
                            CreatedBy = 7L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1596),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1597),
                            Description = "Necessitatibus consectetur repellendus amet ea.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1598),
                            Title = "Voluptate quia."
                        },
                        new
                        {
                            Id = 22L,
                            CreatedBy = 8L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1701),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1702),
                            Description = "Nam accusantium qui molestias aut voluptate est nulla veniam.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1704),
                            Title = "Omnis."
                        },
                        new
                        {
                            Id = 23L,
                            CreatedBy = 8L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1739),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1740),
                            Description = "Sunt omnis autem vero et sed.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1741),
                            Title = "Veniam."
                        },
                        new
                        {
                            Id = 24L,
                            CreatedBy = 8L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1785),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1786),
                            Description = "Alias maxime omnis tempore eius consequuntur rerum nesciunt qui.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1787),
                            Title = "Occaecati porro."
                        },
                        new
                        {
                            Id = 25L,
                            CreatedBy = 9L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1828),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1829),
                            Description = "Repudiandae nemo praesentium autem molestiae harum id et.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1830),
                            Title = "Quis voluptas."
                        },
                        new
                        {
                            Id = 26L,
                            CreatedBy = 9L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1873),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1874),
                            Description = "Doloremque nemo dolorum ipsa et sit dolores velit tenetur consequuntur.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1875),
                            Title = "Eos blanditiis."
                        },
                        new
                        {
                            Id = 27L,
                            CreatedBy = 9L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1949),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1951),
                            Description = "Quod porro aut dolorem saepe ut temporibus repellat consequatur.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(1952),
                            Title = "Et."
                        },
                        new
                        {
                            Id = 28L,
                            CreatedBy = 10L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(2001),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(2002),
                            Description = "Consequatur qui nemo debitis enim molestiae omnis voluptates pariatur aut.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(2003),
                            Title = "Omnis eos."
                        },
                        new
                        {
                            Id = 29L,
                            CreatedBy = 10L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(2043),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(2044),
                            Description = "Neque minus hic odio voluptatem itaque et hic.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(2045),
                            Title = "A perferendis."
                        },
                        new
                        {
                            Id = 30L,
                            CreatedBy = 10L,
                            CreationDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(2088),
                            Deadline = new DateTime(2022, 6, 6, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(2089),
                            Description = "Explicabo voluptas ea est quod non ea nesciunt sint eos.",
                            LastUpdatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 860, DateTimeKind.Utc).AddTicks(2091),
                            Title = "Non consequuntur."
                        });
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 851, DateTimeKind.Utc).AddTicks(2841),
                            Email = "ColtonRunolfsson_Schaefer58@yahoo.com",
                            Name = "Colton Runolfsson",
                            Password = "HHT6ZBh71OnufroWa1pYZEAvE1Yp731zVR2GMYFSHMCPAo1SLxJlwe9e9FeXel_KOaLG2I7EoYmS9FWQMUy3_mC5UXH1MonqBjtCuudnQm38rDrkaf6v5kLU26A82DIn"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 851, DateTimeKind.Utc).AddTicks(3493),
                            Email = "LambertKohler_Hand41@gmail.com",
                            Name = "Lambert Kohler",
                            Password = "qzDGqPrwTpaUMwKq9C_cK92gUFfqbAftqdi8j9EWoLs8TzQCUVP_7rx3c4hirGfWJTEKswJrWGFFHTDQgEpSzKeVZZVRgTUfyfnhvC9oiDZ3oKUg0gA4fs_6SWctY2Z_"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 851, DateTimeKind.Utc).AddTicks(4019),
                            Email = "CamdenHodkiewicz99@gmail.com",
                            Name = "Camden Hodkiewicz",
                            Password = "kts2X267JC7t7_mZ1LGRIqvEhMV0JaevnivDPL3r5YjBnuy0fiXlUdEs0DXyvEQbIPOuWwME2iT7KeBk0kaOBQffdfoWfubFbejeqS3O1lOOKg86biufTRndTzSFIrVv"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 851, DateTimeKind.Utc).AddTicks(4582),
                            Email = "EvanGrady.Mertz35@yahoo.com",
                            Name = "Evan Grady",
                            Password = "_W5hGqiA4gYavBBoD_e0qI246aJ_yy_3IOwoVYmqJ7eeepUA81FJWlEInWtQaKJWl3KNNJwzotmE476xHjqdKflvH6lTvLKR3sNeShy2wSw2RSDSl7BMLPm0r22wB2d6"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 851, DateTimeKind.Utc).AddTicks(5116),
                            Email = "TyrellWintheiser61@hotmail.com",
                            Name = "Tyrell Wintheiser",
                            Password = "jBZtbNgk7OABX6dmdQrO0xAGKsSUGFSWzoSPQlKm4lx7y8MXYcmnJpGR3Ykv3ZMOsVInSt2gUTzqwtZcLBTXG_Hu3jDWtApaaDfZvA6j4BsNQvjCE4KsrXn1gnA8N8UM"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 851, DateTimeKind.Utc).AddTicks(5643),
                            Email = "KatlynnSenger_Bernhard@yahoo.com",
                            Name = "Katlynn Senger",
                            Password = "4J2NiciuIJxycZD9mZdShBhEajYDPVEUa1zbL1axzHdkwWPlE3LX1mO9YBvdcmcNyFmo49sPpxEyHy3iqy4E2clwtct06eF9SRT7ifhmsmrAMBzJolBD3UiHIW_3X9iK"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 851, DateTimeKind.Utc).AddTicks(6219),
                            Email = "GinoGraham39@hotmail.com",
                            Name = "Gino Graham",
                            Password = "eqgPABSk7lEm6SM9LP_ZJuPoAg1AvwT8A82jSmHiDPZuOSQMuySFlYonyD248bcR3wloUqUqie0Itg7DEbWUNoLo4nDc1fdQmEAQTRHw91kNH9YBUXoCx9JaWQd0zJxs"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 851, DateTimeKind.Utc).AddTicks(6847),
                            Email = "MonserratSauer_Ritchie13@hotmail.com",
                            Name = "Monserrat Sauer",
                            Password = "QhhqzoXaSwTkZZlOdUWv35LN8qlrWvHgH0PcJMh8M535H2ZTx4DeUOFd5IDKbtMbGNJK_21EBmvH1Lm5ZSnqNDzi9frjhamlS_mquwCY_5l4ZoRQLJXSeZgQiFHfxFZe"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 851, DateTimeKind.Utc).AddTicks(7378),
                            Email = "ConnieEffertz.Brown@gmail.com",
                            Name = "Connie Effertz",
                            Password = "eCcz0CmCUwTgPEkXthSrkNOb1nNN8O1R7KqAyeHh0NiLKSTnWsxj4VQdVuU6JQC9TbCPcEYdnHp59Hjoq_3K1IH0V57VbvuAxWv4sJpZvPVqXnkGCPoRqbMC6QsnsCXD"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 31, 4, 851, DateTimeKind.Utc).AddTicks(7897),
                            Email = "WillardGutkowski.Kshlerin3@hotmail.com",
                            Name = "Willard Gutkowski",
                            Password = "fkxrsA9AXurQHbqlONFbAoHfdwQt7fn8Q9PUfJ8JuE54jamnEs5g_ngStT7RdqcbnZkg55gF7uEpG3hM8wdavDfC9VXCl4vuzo6qWv9tF82DM3oe5ebJaYUEcmrRHt6b"
                        });
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.TaskKeeper", b =>
                {
                    b.HasOne("WebApiMasterTemplate.Domain.DbModels.TaskTracker", "TaskTracker")
                        .WithMany("TaskKeepers")
                        .HasForeignKey("TaskTrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskTracker");
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.TaskTracker", b =>
                {
                    b.HasOne("WebApiMasterTemplate.Domain.DbModels.User", "User")
                        .WithMany("TaskTrackers")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.TaskTracker", b =>
                {
                    b.Navigation("TaskKeepers");
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.User", b =>
                {
                    b.Navigation("TaskTrackers");
                });
#pragma warning restore 612, 618
        }
    }
}
