// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiMasterTemplate.Domain.DbContexts;

#nullable disable

namespace WebApiMasterTemplate.Domain.Migrations
{
    [DbContext(typeof(TaskPlannerDbContext))]
    [Migration("20220530031614_Added task tracker seed")]
    partial class Addedtasktrackerseed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.TaskKeeper", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<long>("TaskTrackerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TaskTrackerId");

                    b.ToTable("Task", (string)null);
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.TaskTracker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("TaskTracker", (string)null);
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 16, 13, 740, DateTimeKind.Utc).AddTicks(4604),
                            Email = "KelsieTurner14@hotmail.com",
                            Name = "Kelsie Turner",
                            Password = "odd07TV66wbdS2x9MiNYxAyVdihGF8GRdgaMdof7kCWHtgSDy7HttU8fqcuthCoj_v3gjj4De2zltuOnVy7CheI_DNSnb0uVhHRgLbnCr9mw0wn_g6jXt8eRi1FgE93p"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 16, 13, 740, DateTimeKind.Utc).AddTicks(6202),
                            Email = "OmaDurgan.Klein24@hotmail.com",
                            Name = "Oma Durgan",
                            Password = "N_QKg_i0V_YXpKq2ci1RsBTFNxZT9NGpPjA6KQlmge6JeOIx96UOjNisG4fvXKqCIMJBHFZCBdhpRjgtCJC8tWhBzvOromI1ZxwXq8gEtR3a0YuL4K7ZMn1h4RPRtErd"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 16, 13, 740, DateTimeKind.Utc).AddTicks(7229),
                            Email = "DominicCrooks.Yundt@hotmail.com",
                            Name = "Dominic Crooks",
                            Password = "U5wchkdFSk4uHUMvspsBzvb7_awHOYkotwSgCrHqZ3jMhrjAcYUDKIRZh95zGzj0Cepi9u8dA4PKW8i8vVnSRJFfdug6vaTxdQJAnGb4kLxNyoGI5f2BPFEZAjoYcw5N"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 16, 13, 740, DateTimeKind.Utc).AddTicks(8341),
                            Email = "KatrineErnser49@hotmail.com",
                            Name = "Katrine Ernser",
                            Password = "ClxKudvUCH_G6hNwZtkLjDbA9_4taUwYEL3iFtCAYA7fVftKOeyKUyOk3YdmxFSvv5fnF3fTWzcBveh9Sz6CSQoAGtOZNQMXnMkD6WbTeDiO7O1VMjyZblUjEni_vq6R"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 16, 13, 740, DateTimeKind.Utc).AddTicks(9576),
                            Email = "ChynaHowell_Stamm62@yahoo.com",
                            Name = "Chyna Howell",
                            Password = "xzKqrnyWcxHQYlpiNgSrs8WJJOg_1m6b7XiImNV1PyBmNcf9cr2cbK4jk02sg8qw8CDLVX35a0SCeGnNwsAgKqVGIMJbwT0aXySfyjlweq5P48taIrD41p__NiKrXHrS"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 16, 13, 741, DateTimeKind.Utc).AddTicks(860),
                            Email = "WillaLynch20@hotmail.com",
                            Name = "Willa Lynch",
                            Password = "X9fvmJx4Gl3HWPl7Sd9E6tc97fwz1pG32sA202Ef0JN3bhkMuaqPnekJy7DqugnCKJHjb99E47cEaP3AvvGRA7onSjxKlkqymLMto0bh7oy2QFKaCIxIHDVscs8F8LB3"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 16, 13, 741, DateTimeKind.Utc).AddTicks(1944),
                            Email = "RettaFeeney_Runte77@hotmail.com",
                            Name = "Retta Feeney",
                            Password = "eu2z5pApg5CVRViM0mR5UejvcxA7pxnGDOT1zWAQ1f3iXrkIlIhz7oobw2T7auyuIhzIXutH15nDTwlKRScad1zXXnr2WCR2MrsR2bg2gGmtpupkSungBM6jHdIUINlW"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 16, 13, 741, DateTimeKind.Utc).AddTicks(3155),
                            Email = "RodolfoMetz_Bogisich82@hotmail.com",
                            Name = "Rodolfo Metz",
                            Password = "kfrS602tTxKkue4f9gVJ1d1HJc9tMBjgxQ9Y8wRkTFkEnmVmjgGF33pxGPY9yGENpUknigA8iQMR90DAO3buVieGQ9Y9y6jPP_DBFXrotLz9bHXOfqf7ysDv0wqGnRQf"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 16, 13, 741, DateTimeKind.Utc).AddTicks(4362),
                            Email = "FlorineTurcotte.Schaefer21@yahoo.com",
                            Name = "Florine Turcotte",
                            Password = "beyawg7dwZpFqmOwiBpOqfdXpP1KELBmW6_9UY8KjNZLhGAm9EmxzYmxanzApV7ov7eCj7rfIxmpZzulU4aUq9dJOmblqETbnlN6E4R3FWfvH9Avcu_gthNU5EhlOeWj"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedDate = new DateTime(2022, 5, 30, 3, 16, 13, 741, DateTimeKind.Utc).AddTicks(5491),
                            Email = "RogerSpinka.McCullough75@gmail.com",
                            Name = "Roger Spinka",
                            Password = "nPAnhlINMg7P61hwRw6YQR_80gSDsDuXfdLFEI35Q4YnDzcLV7qYQuXbADX6j27oAyRSOQPjAeN_QDrMh0tb8R6dNKC5MIUK5HkNHb0o_KPGYYppHX2gng3hC62YyXTy"
                        });
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.TaskKeeper", b =>
                {
                    b.HasOne("WebApiMasterTemplate.Domain.DbModels.TaskTracker", "TaskTracker")
                        .WithMany("TaskKeepers")
                        .HasForeignKey("TaskTrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskTracker");
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.TaskTracker", b =>
                {
                    b.HasOne("WebApiMasterTemplate.Domain.DbModels.User", "User")
                        .WithMany("TaskTrackers")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.TaskTracker", b =>
                {
                    b.Navigation("TaskKeepers");
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.User", b =>
                {
                    b.Navigation("TaskTrackers");
                });
#pragma warning restore 612, 618
        }
    }
}
