// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiMasterTemplate.Domain.DbContexts;

#nullable disable

namespace WebApiMasterTemplate.Domain.Migrations
{
    [DbContext(typeof(TaskPlannerDbContext))]
    [Migration("20220709164201_Added JWT services")]
    partial class AddedJWTservices
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.TaskKeeper", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<long>("TaskTrackerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TaskTrackerId");

                    b.ToTable("Task", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 1L,
                            Title = "Veniam."
                        },
                        new
                        {
                            Id = 2L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 1L,
                            Title = "Dolore."
                        },
                        new
                        {
                            Id = 3L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 1L,
                            Title = "Accusamus consectetur."
                        },
                        new
                        {
                            Id = 4L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 1L,
                            Title = "Adipisci ea."
                        },
                        new
                        {
                            Id = 5L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 1L,
                            Title = "Dolorem."
                        },
                        new
                        {
                            Id = 6L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 2L,
                            Title = "Ut."
                        },
                        new
                        {
                            Id = 7L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 2L,
                            Title = "Repudiandae."
                        },
                        new
                        {
                            Id = 8L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 2L,
                            Title = "Earum voluptatibus."
                        },
                        new
                        {
                            Id = 9L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 2L,
                            Title = "Voluptatum."
                        },
                        new
                        {
                            Id = 10L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 2L,
                            Title = "Ut et."
                        },
                        new
                        {
                            Id = 11L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 3L,
                            Title = "Consequatur est."
                        },
                        new
                        {
                            Id = 12L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 3L,
                            Title = "Provident recusandae."
                        },
                        new
                        {
                            Id = 13L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 3L,
                            Title = "Repellendus."
                        },
                        new
                        {
                            Id = 14L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 3L,
                            Title = "Delectus vel."
                        },
                        new
                        {
                            Id = 15L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 3L,
                            Title = "Nihil iste."
                        },
                        new
                        {
                            Id = 16L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 4L,
                            Title = "Dolorem veniam."
                        },
                        new
                        {
                            Id = 17L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 4L,
                            Title = "Non."
                        },
                        new
                        {
                            Id = 18L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 4L,
                            Title = "Et error."
                        },
                        new
                        {
                            Id = 19L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 4L,
                            Title = "Commodi."
                        },
                        new
                        {
                            Id = 20L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 4L,
                            Title = "Nisi unde."
                        },
                        new
                        {
                            Id = 21L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 5L,
                            Title = "Sint temporibus."
                        },
                        new
                        {
                            Id = 22L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 5L,
                            Title = "A."
                        },
                        new
                        {
                            Id = 23L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 5L,
                            Title = "At."
                        },
                        new
                        {
                            Id = 24L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 5L,
                            Title = "Repellat repudiandae."
                        },
                        new
                        {
                            Id = 25L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 5L,
                            Title = "Fugiat accusamus."
                        },
                        new
                        {
                            Id = 26L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 6L,
                            Title = "Tenetur."
                        },
                        new
                        {
                            Id = 27L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 6L,
                            Title = "Saepe."
                        },
                        new
                        {
                            Id = 28L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 6L,
                            Title = "Omnis est."
                        },
                        new
                        {
                            Id = 29L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 6L,
                            Title = "Temporibus."
                        },
                        new
                        {
                            Id = 30L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 6L,
                            Title = "Quidem."
                        },
                        new
                        {
                            Id = 31L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 7L,
                            Title = "Quaerat."
                        },
                        new
                        {
                            Id = 32L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 7L,
                            Title = "Assumenda perspiciatis."
                        },
                        new
                        {
                            Id = 33L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 7L,
                            Title = "Eligendi aut."
                        },
                        new
                        {
                            Id = 34L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 7L,
                            Title = "Saepe."
                        },
                        new
                        {
                            Id = 35L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 7L,
                            Title = "Omnis ab."
                        },
                        new
                        {
                            Id = 36L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 8L,
                            Title = "Et."
                        },
                        new
                        {
                            Id = 37L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 8L,
                            Title = "Quidem."
                        },
                        new
                        {
                            Id = 38L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 8L,
                            Title = "Laboriosam voluptatem."
                        },
                        new
                        {
                            Id = 39L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 8L,
                            Title = "Dolores."
                        },
                        new
                        {
                            Id = 40L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 8L,
                            Title = "Tempore nihil."
                        },
                        new
                        {
                            Id = 41L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 9L,
                            Title = "Rerum qui."
                        },
                        new
                        {
                            Id = 42L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 9L,
                            Title = "Qui."
                        },
                        new
                        {
                            Id = 43L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 9L,
                            Title = "Magnam."
                        },
                        new
                        {
                            Id = 44L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 9L,
                            Title = "Error ipsum."
                        },
                        new
                        {
                            Id = 45L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 9L,
                            Title = "Praesentium."
                        },
                        new
                        {
                            Id = 46L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 10L,
                            Title = "Aliquam magnam."
                        },
                        new
                        {
                            Id = 47L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 10L,
                            Title = "Nostrum."
                        },
                        new
                        {
                            Id = 48L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 10L,
                            Title = "Dolor aperiam."
                        },
                        new
                        {
                            Id = 49L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 10L,
                            Title = "Asperiores."
                        },
                        new
                        {
                            Id = 50L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 10L,
                            Title = "Nam."
                        },
                        new
                        {
                            Id = 51L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 11L,
                            Title = "Tempore excepturi."
                        },
                        new
                        {
                            Id = 52L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 11L,
                            Title = "Debitis."
                        },
                        new
                        {
                            Id = 53L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 11L,
                            Title = "Doloribus suscipit."
                        },
                        new
                        {
                            Id = 54L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 11L,
                            Title = "Voluptatum."
                        },
                        new
                        {
                            Id = 55L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 11L,
                            Title = "Vel."
                        },
                        new
                        {
                            Id = 56L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 12L,
                            Title = "Consequatur fugit."
                        },
                        new
                        {
                            Id = 57L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 12L,
                            Title = "Eligendi."
                        },
                        new
                        {
                            Id = 58L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 12L,
                            Title = "Beatae ipsam."
                        },
                        new
                        {
                            Id = 59L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 12L,
                            Title = "Assumenda."
                        },
                        new
                        {
                            Id = 60L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 12L,
                            Title = "Quod magnam."
                        },
                        new
                        {
                            Id = 61L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 13L,
                            Title = "Accusantium."
                        },
                        new
                        {
                            Id = 62L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 13L,
                            Title = "Beatae."
                        },
                        new
                        {
                            Id = 63L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 13L,
                            Title = "Est minima."
                        },
                        new
                        {
                            Id = 64L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 13L,
                            Title = "Ullam."
                        },
                        new
                        {
                            Id = 65L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 13L,
                            Title = "Provident."
                        },
                        new
                        {
                            Id = 66L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 14L,
                            Title = "Pariatur."
                        },
                        new
                        {
                            Id = 67L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 14L,
                            Title = "Et."
                        },
                        new
                        {
                            Id = 68L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 14L,
                            Title = "Quos suscipit."
                        },
                        new
                        {
                            Id = 69L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 14L,
                            Title = "Voluptas non."
                        },
                        new
                        {
                            Id = 70L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 14L,
                            Title = "Consequatur."
                        },
                        new
                        {
                            Id = 71L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 15L,
                            Title = "Quas."
                        },
                        new
                        {
                            Id = 72L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 15L,
                            Title = "Maiores."
                        },
                        new
                        {
                            Id = 73L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 15L,
                            Title = "Est."
                        },
                        new
                        {
                            Id = 74L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 15L,
                            Title = "Ex necessitatibus."
                        },
                        new
                        {
                            Id = 75L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 15L,
                            Title = "Amet assumenda."
                        },
                        new
                        {
                            Id = 76L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 16L,
                            Title = "Nisi labore."
                        },
                        new
                        {
                            Id = 77L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 16L,
                            Title = "Et voluptas."
                        },
                        new
                        {
                            Id = 78L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 16L,
                            Title = "Consequatur exercitationem."
                        },
                        new
                        {
                            Id = 79L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 16L,
                            Title = "Repellendus blanditiis."
                        },
                        new
                        {
                            Id = 80L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 16L,
                            Title = "Ipsa quis."
                        },
                        new
                        {
                            Id = 81L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 17L,
                            Title = "Natus illum."
                        },
                        new
                        {
                            Id = 82L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 17L,
                            Title = "Aliquam illo."
                        },
                        new
                        {
                            Id = 83L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 17L,
                            Title = "Explicabo."
                        },
                        new
                        {
                            Id = 84L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 17L,
                            Title = "Deleniti."
                        },
                        new
                        {
                            Id = 85L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 17L,
                            Title = "Voluptatem sunt."
                        },
                        new
                        {
                            Id = 86L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 18L,
                            Title = "Maxime sit."
                        },
                        new
                        {
                            Id = 87L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 18L,
                            Title = "Nesciunt voluptatem."
                        },
                        new
                        {
                            Id = 88L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 18L,
                            Title = "Ut."
                        },
                        new
                        {
                            Id = 89L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 18L,
                            Title = "Qui."
                        },
                        new
                        {
                            Id = 90L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 18L,
                            Title = "Aut quod."
                        },
                        new
                        {
                            Id = 91L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 19L,
                            Title = "Minima atque."
                        },
                        new
                        {
                            Id = 92L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 19L,
                            Title = "Rerum consequatur."
                        },
                        new
                        {
                            Id = 93L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 19L,
                            Title = "Iure."
                        },
                        new
                        {
                            Id = 94L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 19L,
                            Title = "Dolorem repellendus."
                        },
                        new
                        {
                            Id = 95L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 19L,
                            Title = "Incidunt."
                        },
                        new
                        {
                            Id = 96L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 20L,
                            Title = "Sint."
                        },
                        new
                        {
                            Id = 97L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 20L,
                            Title = "Consequuntur et."
                        },
                        new
                        {
                            Id = 98L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 20L,
                            Title = "Et."
                        },
                        new
                        {
                            Id = 99L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 20L,
                            Title = "Molestiae."
                        },
                        new
                        {
                            Id = 100L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 20L,
                            Title = "Blanditiis id."
                        },
                        new
                        {
                            Id = 101L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 21L,
                            Title = "Optio."
                        },
                        new
                        {
                            Id = 102L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 21L,
                            Title = "Odit."
                        },
                        new
                        {
                            Id = 103L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 21L,
                            Title = "Delectus."
                        },
                        new
                        {
                            Id = 104L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 21L,
                            Title = "Aut consequatur."
                        },
                        new
                        {
                            Id = 105L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 21L,
                            Title = "Nesciunt ea."
                        },
                        new
                        {
                            Id = 106L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 22L,
                            Title = "Tenetur."
                        },
                        new
                        {
                            Id = 107L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 22L,
                            Title = "Aut quis."
                        },
                        new
                        {
                            Id = 108L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 22L,
                            Title = "Velit aut."
                        },
                        new
                        {
                            Id = 109L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 22L,
                            Title = "Officia omnis."
                        },
                        new
                        {
                            Id = 110L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 22L,
                            Title = "Fugit."
                        },
                        new
                        {
                            Id = 111L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 23L,
                            Title = "Asperiores."
                        },
                        new
                        {
                            Id = 112L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 23L,
                            Title = "Cumque."
                        },
                        new
                        {
                            Id = 113L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 23L,
                            Title = "Facilis autem."
                        },
                        new
                        {
                            Id = 114L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 23L,
                            Title = "Harum."
                        },
                        new
                        {
                            Id = 115L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 23L,
                            Title = "Enim et."
                        },
                        new
                        {
                            Id = 116L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 24L,
                            Title = "Assumenda."
                        },
                        new
                        {
                            Id = 117L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 24L,
                            Title = "Consequatur nulla."
                        },
                        new
                        {
                            Id = 118L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 24L,
                            Title = "Vero."
                        },
                        new
                        {
                            Id = 119L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 24L,
                            Title = "Minima."
                        },
                        new
                        {
                            Id = 120L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 24L,
                            Title = "Laudantium."
                        },
                        new
                        {
                            Id = 121L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 25L,
                            Title = "Adipisci ab."
                        },
                        new
                        {
                            Id = 122L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 25L,
                            Title = "Et natus."
                        },
                        new
                        {
                            Id = 123L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 25L,
                            Title = "Aut."
                        },
                        new
                        {
                            Id = 124L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 25L,
                            Title = "Veritatis harum."
                        },
                        new
                        {
                            Id = 125L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 25L,
                            Title = "Ea."
                        },
                        new
                        {
                            Id = 126L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 26L,
                            Title = "Fugiat."
                        },
                        new
                        {
                            Id = 127L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 26L,
                            Title = "Ratione."
                        },
                        new
                        {
                            Id = 128L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 26L,
                            Title = "Necessitatibus omnis."
                        },
                        new
                        {
                            Id = 129L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 26L,
                            Title = "Saepe sint."
                        },
                        new
                        {
                            Id = 130L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 26L,
                            Title = "Fuga molestias."
                        },
                        new
                        {
                            Id = 131L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 27L,
                            Title = "Praesentium et."
                        },
                        new
                        {
                            Id = 132L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 27L,
                            Title = "Possimus."
                        },
                        new
                        {
                            Id = 133L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 27L,
                            Title = "Possimus temporibus."
                        },
                        new
                        {
                            Id = 134L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 27L,
                            Title = "Aut."
                        },
                        new
                        {
                            Id = 135L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 27L,
                            Title = "Quia."
                        },
                        new
                        {
                            Id = 136L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 28L,
                            Title = "Nihil nihil."
                        },
                        new
                        {
                            Id = 137L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 28L,
                            Title = "Tempora inventore."
                        },
                        new
                        {
                            Id = 138L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 28L,
                            Title = "Cum et."
                        },
                        new
                        {
                            Id = 139L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 28L,
                            Title = "Magnam totam."
                        },
                        new
                        {
                            Id = 140L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 28L,
                            Title = "Sed dolores."
                        },
                        new
                        {
                            Id = 141L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 29L,
                            Title = "Est et."
                        },
                        new
                        {
                            Id = 142L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 29L,
                            Title = "Atque laborum."
                        },
                        new
                        {
                            Id = 143L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 2,
                            TaskTrackerId = 29L,
                            Title = "Modi commodi."
                        },
                        new
                        {
                            Id = 144L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 29L,
                            Title = "Deserunt magni."
                        },
                        new
                        {
                            Id = 145L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 29L,
                            Title = "Dolores."
                        },
                        new
                        {
                            Id = 146L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 30L,
                            Title = "Dolores."
                        },
                        new
                        {
                            Id = 147L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 30L,
                            Title = "Vel non."
                        },
                        new
                        {
                            Id = 148L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 3,
                            TaskTrackerId = 30L,
                            Title = "Enim."
                        },
                        new
                        {
                            Id = 149L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 4,
                            TaskTrackerId = 30L,
                            Title = "Commodi."
                        },
                        new
                        {
                            Id = 150L,
                            Deadline = new DateTime(2022, 7, 10, 16, 42, 0, 724, DateTimeKind.Utc).AddTicks(8472),
                            State = 1,
                            TaskTrackerId = 30L,
                            Title = "Et."
                        });
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.TaskTracker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("TaskTracker", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = 1L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(4222),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(4272),
                            Description = "Explicabo id quia omnis omnis.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(4309),
                            Title = "Officiis."
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = 1L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(4392),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(4394),
                            Description = "Corporis eligendi consequuntur occaecati quia.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(4396),
                            Title = "Eveniet."
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = 1L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(4538),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(4543),
                            Description = "Facere excepturi recusandae possimus rem sint similique corporis sit.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(4548),
                            Title = "Beatae dolorum."
                        },
                        new
                        {
                            Id = 4L,
                            CreatedBy = 2L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(4713),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(4718),
                            Description = "Totam consequatur molestiae aut illum.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(4722),
                            Title = "Nam aperiam."
                        },
                        new
                        {
                            Id = 5L,
                            CreatedBy = 2L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(4948),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(4953),
                            Description = "In rem ex dolore consectetur autem.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(4957),
                            Title = "Ad aut."
                        },
                        new
                        {
                            Id = 6L,
                            CreatedBy = 2L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5080),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5083),
                            Description = "Ipsam est et dicta enim rerum asperiores.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5086),
                            Title = "Autem."
                        },
                        new
                        {
                            Id = 7L,
                            CreatedBy = 3L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5174),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5176),
                            Description = "Sed et qui dolor harum nemo.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5177),
                            Title = "Ab."
                        },
                        new
                        {
                            Id = 8L,
                            CreatedBy = 3L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5233),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5234),
                            Description = "Animi corrupti pariatur enim earum quia est distinctio consectetur qui.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5235),
                            Title = "Totam rerum."
                        },
                        new
                        {
                            Id = 9L,
                            CreatedBy = 3L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5286),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5287),
                            Description = "Nihil omnis ut excepturi soluta aperiam molestias vel molestiae qui.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5288),
                            Title = "Necessitatibus repellat."
                        },
                        new
                        {
                            Id = 10L,
                            CreatedBy = 4L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5444),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5448),
                            Description = "Nulla mollitia nesciunt inventore ex neque occaecati vero magnam.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5453),
                            Title = "Possimus reiciendis."
                        },
                        new
                        {
                            Id = 11L,
                            CreatedBy = 4L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5597),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5599),
                            Description = "Neque perferendis cumque provident recusandae quisquam ipsum velit delectus.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5601),
                            Title = "Eveniet."
                        },
                        new
                        {
                            Id = 12L,
                            CreatedBy = 4L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5660),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5661),
                            Description = "Reiciendis ut ex laudantium odit.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5662),
                            Title = "Aspernatur sit."
                        },
                        new
                        {
                            Id = 13L,
                            CreatedBy = 5L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5697),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5697),
                            Description = "Molestias consequatur inventore recusandae sapiente.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5699),
                            Title = "Consequatur laudantium."
                        },
                        new
                        {
                            Id = 14L,
                            CreatedBy = 5L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5742),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5743),
                            Description = "Quod quasi dolor libero quia aut aut et perspiciatis.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5744),
                            Title = "Est."
                        },
                        new
                        {
                            Id = 15L,
                            CreatedBy = 5L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5817),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5818),
                            Description = "Et necessitatibus deserunt veniam et consectetur quisquam.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5819),
                            Title = "Voluptatem."
                        },
                        new
                        {
                            Id = 16L,
                            CreatedBy = 6L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5867),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5868),
                            Description = "Molestiae et sit beatae vel accusantium rerum quia quaerat deserunt.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5870),
                            Title = "Eaque."
                        },
                        new
                        {
                            Id = 17L,
                            CreatedBy = 6L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5917),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5917),
                            Description = "Sapiente et ullam blanditiis libero omnis consectetur distinctio atque.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5918),
                            Title = "A recusandae."
                        },
                        new
                        {
                            Id = 18L,
                            CreatedBy = 6L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5966),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5967),
                            Description = "Quo aliquid ex et ipsam sunt iste quibusdam placeat quia.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(5968),
                            Title = "Ab esse."
                        },
                        new
                        {
                            Id = 19L,
                            CreatedBy = 7L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6014),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6015),
                            Description = "Fuga beatae sint rerum dolor sunt est illum est exercitationem.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6016),
                            Title = "Facere."
                        },
                        new
                        {
                            Id = 20L,
                            CreatedBy = 7L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6086),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6087),
                            Description = "Aspernatur beatae odio ut et ut aut sit sed.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6088),
                            Title = "Aliquam inventore."
                        },
                        new
                        {
                            Id = 21L,
                            CreatedBy = 7L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6119),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6120),
                            Description = "Sunt molestias ea corporis et.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6121),
                            Title = "Quis."
                        },
                        new
                        {
                            Id = 22L,
                            CreatedBy = 8L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6159),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6160),
                            Description = "Fuga sequi voluptatem ut adipisci aut explicabo.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6161),
                            Title = "Vero id."
                        },
                        new
                        {
                            Id = 23L,
                            CreatedBy = 8L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6204),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6205),
                            Description = "Possimus sed in est sit soluta consequatur quia eum atque.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6206),
                            Title = "Sapiente voluptas."
                        },
                        new
                        {
                            Id = 24L,
                            CreatedBy = 8L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6239),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6240),
                            Description = "Aut quo vel molestiae tempora quasi facere.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6240),
                            Title = "Nihil."
                        },
                        new
                        {
                            Id = 25L,
                            CreatedBy = 9L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6270),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6271),
                            Description = "Soluta impedit officia et et.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6272),
                            Title = "Est."
                        },
                        new
                        {
                            Id = 26L,
                            CreatedBy = 9L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6348),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6349),
                            Description = "Quia corrupti inventore voluptatem eos consequuntur quidem eos laborum consequuntur.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6350),
                            Title = "A."
                        },
                        new
                        {
                            Id = 27L,
                            CreatedBy = 9L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6406),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6407),
                            Description = "Quos reprehenderit recusandae hic aliquam perspiciatis non.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6408),
                            Title = "Eligendi."
                        },
                        new
                        {
                            Id = 28L,
                            CreatedBy = 10L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6447),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6448),
                            Description = "Labore rerum enim magni soluta esse natus harum.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6449),
                            Title = "Et eos."
                        },
                        new
                        {
                            Id = 29L,
                            CreatedBy = 10L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6490),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6491),
                            Description = "Ab reprehenderit nesciunt corporis dolorum modi harum quo et.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6492),
                            Title = "Enim."
                        },
                        new
                        {
                            Id = 30L,
                            CreatedBy = 10L,
                            CreationDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6522),
                            Deadline = new DateTime(2022, 7, 16, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6523),
                            Description = "Consequatur et quidem accusamus totam.",
                            LastUpdatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 711, DateTimeKind.Utc).AddTicks(6523),
                            Title = "Non."
                        });
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 696, DateTimeKind.Utc).AddTicks(4435),
                            Email = "SashaOHara.Fadel@gmail.com",
                            Name = "Sasha O'Hara",
                            Password = "hQe6X7EnvN2KYNOcAc_bXBEiSm9IuwDmwMmDsklJwa0OmqLZq1ela_tHexCWTgmF55rEjtJgLyOW6z_tXpO4HnPfWLi0NVC8BIiPJqrEmWtvjB0g6aigmYQjSwVLIxbP"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 696, DateTimeKind.Utc).AddTicks(5216),
                            Email = "IsacBeer_Frami@hotmail.com",
                            Name = "Isac Beer",
                            Password = "tLY7yZXQ2dsHbMQHel2UjZmntcrim5_7M2h4tUjFnx7jfbMRJHwDo2jQx60kydqalvnCuXspUvYHRiyLKZz4UNrKbbMyfbbvycWFlH2TVwEDf8ScXcKnRYQGN1dyLf6A"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 696, DateTimeKind.Utc).AddTicks(5851),
                            Email = "GrahamMayert.Ortiz@gmail.com",
                            Name = "Graham Mayert",
                            Password = "wVQ0oXFnphmE39NQhC4LSdk9IIj3nqcx_zUuOLmaJkY72Y21EPxJzf3GeuT9M2whtw7Atp9jSkNc1zsKQq1r8zdDOjL4a9mS52skG0BU_tIRtxTi_sPzzRa8WecTWYWW"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 696, DateTimeKind.Utc).AddTicks(6650),
                            Email = "KatarinaSchroeder.Spinka@gmail.com",
                            Name = "Katarina Schroeder",
                            Password = "3gGpJcUczxOzmGFslzI4Eg_4Qu3eWg8Qc3i4BtrW_UNteWBUp8riJD2RwQFiO46vsZocFYTGfLclIodGaSnm2MoY5owLGQdVu0lx0unp2SZeyU_HKqCkPY8vspF2N_wY"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 696, DateTimeKind.Utc).AddTicks(7310),
                            Email = "KyleeWisozk_Gulgowski@gmail.com",
                            Name = "Kylee Wisozk",
                            Password = "HmEBF32qT3wZMhoC7_JaayKrMJjxT_E5G4Gl1JVkJbCKdaozIwAyAV3bMqK1hGIeJsYbpAGQCGmXA6C87pRMrYpGxUsHax4ZmZZyRaJ42_UYPVBTZzVf9vKKH32Dq1Pv"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 696, DateTimeKind.Utc).AddTicks(7775),
                            Email = "DanielaMacGyver_Ryan@hotmail.com",
                            Name = "Daniela MacGyver",
                            Password = "DJuJ5hl3nT3U93Le4ykJsmlCHsG1YLv2AWc6H_mgW6bhiuj4SlpkzQYEQcFOJOhskoA0Y7clkJs6Vc7fVSxfVC2OJ0_tuXudmuFfKLOO6HKSUWd1I_hiXbeNOrBSfBBF"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 696, DateTimeKind.Utc).AddTicks(9305),
                            Email = "DaphneeKub_Auer97@yahoo.com",
                            Name = "Daphnee Kub",
                            Password = "1IKOjkC6byzPsRPAiACRqoYHzqhuMxTtaS8CdEkD9fjCE3QNIJUk85t2glZJ5WCKcZTPZZ8qdLl7u9gke80lQfiKXegXVI1Y5_IGPNTlIGscfXN4g8PtjH2JJFaxsgyb"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 697, DateTimeKind.Utc).AddTicks(110),
                            Email = "CarleeNikolaus_Gibson@yahoo.com",
                            Name = "Carlee Nikolaus",
                            Password = "HKoH12zCzyx9LxyL4m5DjwGv2w4BBGodEVxej8xflEDF0yG4gFuC1J7jNRlKxSgzJHUiYoGdWoTOk_N3HysAv95W8gWrYBbl4tRZWZfED7Q69QiPbHTv7pHeroUGgtUv"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 697, DateTimeKind.Utc).AddTicks(665),
                            Email = "MustafaEffertz.Graham61@yahoo.com",
                            Name = "Mustafa Effertz",
                            Password = "EtGFvEzzQreTPwUneXhjKiHSWVowWLe1LNIRkT7Ve8Cd7oycb9SKuX0AJ28JvGYUu4TvVQ0Bv55p7tyE6wPBXtk6VtCaDoeOveSfq7pJRhWG3IyydlMRR9F1yjWIV3f_"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedDate = new DateTime(2022, 7, 9, 16, 42, 0, 697, DateTimeKind.Utc).AddTicks(1173),
                            Email = "BlancaSchultz.Rice@hotmail.com",
                            Name = "Blanca Schultz",
                            Password = "gC7uMqAqLc03CDJTceF9kFnHztbsXWt_Uqy5hnWNHALvQHLbw_GjlfTZEnCcvhfOybbKG6jfnrVs3u7TbOL9Qn2YzKlu2tW7wGgEVCEmJaHxvrTVC1pWpCDiHSdC0i8U"
                        });
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.TaskKeeper", b =>
                {
                    b.HasOne("WebApiMasterTemplate.Domain.DbModels.TaskTracker", "TaskTracker")
                        .WithMany("TaskKeepers")
                        .HasForeignKey("TaskTrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskTracker");
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.TaskTracker", b =>
                {
                    b.HasOne("WebApiMasterTemplate.Domain.DbModels.User", "User")
                        .WithMany("TaskTrackers")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.TaskTracker", b =>
                {
                    b.Navigation("TaskKeepers");
                });

            modelBuilder.Entity("WebApiMasterTemplate.Domain.DbModels.User", b =>
                {
                    b.Navigation("TaskTrackers");
                });
#pragma warning restore 612, 618
        }
    }
}
